server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pranavchavan19/Config_Server_microservice
          clone-on-start: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://service-regsistry-microservices-hotel.onrender.com/eureka/